[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C03A541250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/33265e7c936e63bb3e4f5b9c1e3230a1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C039912050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/33265e7c936e63bb3e4f5b9c1e3230a1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C03A548ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/33265e7c936e63bb3e4f5b9c1e3230a1