[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017FC6AA0F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b419821b7bc4e8660aca498d0902fdd2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017FC626D710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b419821b7bc4e8660aca498d0902fdd2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017FC6AA1D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b419821b7bc4e8660aca498d0902fdd2